import os
import json
from dfap.investigation.workspace import InvestigationWorkspaceBackend
from dfap.investigation.narrative_generator import (
    NarrativeGeneratorService, NarrativeTemplate, Claim, ClaimType, SourceModule
)
from dfap.investigation.event_sourcing import EventStore
from dfap.investigation.four_domain_fixture import register_four_domain_fixture, FND_4DOM_FUSED

def run_smoke_test():
    print("=== FEATURE 2 SMOKE TEST ===")
    backend = InvestigationWorkspaceBackend(
        output_dir="output", canonical_dir="data/canonical", cases_dir="data/cases"
    )
    register_four_domain_fixture(backend)
    
    event_store = EventStore("data/demo_feature2_events.jsonl")
    gen = NarrativeGeneratorService(backend, event_store=event_store)
    
    print("\n--- 1. Generating INTERNAL_BRIEF for finding FND_4DOM_FUSED_001 ---")
    narrative = gen.generate_narrative(FND_4DOM_FUSED, NarrativeTemplate.INTERNAL_BRIEF)
    
    print("\n--- 2. Structured Narrative ---")
    print(f"Finding ID: {narrative.finding_id}")
    print(f"Template: {narrative.template.value}")
    print(f"Generated By: {narrative.generated_by}")
    
    print("\n--- 3. Individual Claims & 4. Evidence Refs ---")
    for c in narrative.claims:
        print(f"  [{c.claim_type.value}] {c.text} (Refs: {c.evidence_refs}) [Manual Draft: {c.manual_drafting_required}]")
        
    print("\n--- 5. Resolve against M12 ---")
    for c in narrative.claims:
        for ref in c.evidence_refs:
            rec = backend.evidence_engine.evidence_store.get(ref)
            if rec:
                print(f"  Resolved {ref}: {rec.source_domain} / {rec.evidence_type}")
            else:
                print(f"  Failed to resolve {ref}!")
                
    print("\n--- 6. Feature 3 Risk Tier ---")
    print(f"Risk Tier: {narrative.risk_tier}")
    
    print("\n--- 7. M11 conflict/abstention state ---")
    m11_state = gen._get_m11_state("CASE-DFAP-4DOMAIN-001")
    print(f"M11 State: {m11_state.get('overall_status')}")
    
    print("\n--- 8. Forced ABSTAINED claim ---")
    abstained_claims = [c for c in narrative.claims if c.claim_type == ClaimType.ABSTAINED]
    for ac in abstained_claims:
        print(f"  Found ABSTAINED claim: {ac.text}")
        
    print("\n--- 9. Rendered Narrative (INTERNAL_BRIEF) ---")
    print(gen.render_narrative(narrative))
    
    print("\n--- 10. Generate CASE_FILE ---")
    narrative_case = gen.generate_narrative(FND_4DOM_FUSED, NarrativeTemplate.CASE_FILE)
    print(gen.render_narrative(narrative_case))
    
    print("\n--- 11. Generate COURT_SUMMARY & 12. AI_SYNTHESIZED separation ---")
    narrative_court = gen.generate_narrative(FND_4DOM_FUSED, NarrativeTemplate.COURT_SUMMARY)
    print(gen.render_narrative(narrative_court))
    
    print("\n--- 13 & 14. Invalid Citation Rejection & Regeneration ---")
    # Simulate a claim with bad evidence
    bad_claim = Claim(
        text="A fabricated claim with bad evidence.",
        claim_type=ClaimType.DIRECTLY_EVIDENCED,
        evidence_refs=["FAKE_EVID_999"],
        confidence=0.9,
        source_module=SourceModule.M9
    )
    # The valid evidence IDs for FND_4DOM_FUSED
    valid_ev_ids = {e['evidence_id'] for e in gen._get_evidence_context(FND_4DOM_FUSED)}
    print(f"Attempting to validate claim with FAKE_EVID_999...")
    validated = gen._validate_and_retry_claim(bad_claim, valid_ev_ids, FND_4DOM_FUSED, max_retries=2)
    print(f"Resulting claim text: {validated.text}")
    print(f"Manual Drafting Required: {validated.manual_drafting_required}")
    
    print("\n--- 15. Event-log tracking ---")
    print("Edit history events attached to narrative:")
    print(narrative.edit_history)
    print("\n=== SMOKE TEST COMPLETE ===")

if __name__ == "__main__":
    run_smoke_test()
