"""
Domain Enums for Lawful Data Request Module (LDRM).
"""
from enum import Enum

class RequestStatus(str, Enum):
    # Forward happy-path lifecycle states
    DRAFT = "DRAFT"
    VALIDATION_PENDING = "VALIDATION_PENDING"
    LEGAL_REVIEW = "LEGAL_REVIEW"
    AUTHORIZATION_PENDING = "AUTHORIZATION_PENDING"
    AUTHORIZED = "AUTHORIZED"
    SIGNED = "SIGNED"
    READY_TO_SEND = "READY_TO_SEND"
    READY_FOR_MANUAL_SUBMISSION = "READY_FOR_MANUAL_SUBMISSION"
    SENT = "SENT"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    PROVIDER_PROCESSING = "PROVIDER_PROCESSING"
    RESPONSE_PENDING = "RESPONSE_PENDING"
    RESPONSE_RECEIVED = "RESPONSE_RECEIVED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    INGESTED = "INGESTED"
    CLOSED = "CLOSED"

    # Exception states
    REJECTED = "REJECTED"
    NEEDS_CORRECTION = "NEEDS_CORRECTION"
    PROVIDER_QUERY = "PROVIDER_QUERY"
    PARTIAL_RESPONSE = "PARTIAL_RESPONSE"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class AuthorityType(str, Enum):
    COURT_ORDER = "COURT_ORDER"
    WARRANT = "WARRANT"
    SUBPOENA = "SUBPOENA"
    STATUTORY_DIRECTIVE = "STATUTORY_DIRECTIVE"
    EMERGENCY_PROVISION = "EMERGENCY_PROVISION"


class ProviderCategory(str, Enum):
    TELECOM = "TELECOM"
    ISP = "ISP"
    BANK = "BANK"
    PAYMENT_PROVIDER = "PAYMENT_PROVIDER"
    SOCIAL_PLATFORM = "SOCIAL_PLATFORM"
    OTHER = "OTHER"


class DatasetType(str, Enum):
    CDR = "CDR"
    IPDR = "IPDR"
    BANK = "BANK"
    SOCIAL = "SOCIAL"


class TargetType(str, Enum):
    PHONE = "PHONE"
    PHONE_NUMBER = "PHONE_NUMBER"
    IMSI = "IMSI"
    IMEI = "IMEI"
    EMAIL = "EMAIL"
    IP = "IP"
    IP_ADDRESS = "IP_ADDRESS"
    IP_SUBNET = "IP_SUBNET"
    BANK_ACCOUNT = "BANK_ACCOUNT"
    UPI_ID = "UPI_ID"
    SOCIAL_ACCOUNT = "SOCIAL_ACCOUNT"
    SOCIAL_HANDLE = "SOCIAL_HANDLE"
    SUBSCRIBER_ID = "SUBSCRIBER_ID"
    ACCOUNT_ID = "ACCOUNT_ID"
    DEVICE_ID = "DEVICE_ID"
    OTHER = "OTHER"


class Priority(str, Enum):
    ROUTINE = "ROUTINE"
    URGENT = "URGENT"
    EMERGENCY_EXIGENT = "EMERGENCY_EXIGENT"


class ProviderVerificationStatus(str, Enum):
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    SUSPENDED = "SUSPENDED"


class ProviderActiveStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class TransmissionMethod(str, Enum):
    OFFICIAL_EMAIL = "OFFICIAL_EMAIL"
    PROVIDER_PORTAL = "PROVIDER_PORTAL"
    OFFICIAL_API = "OFFICIAL_API"
    GOVERNMENT_GATEWAY = "GOVERNMENT_GATEWAY"
    SECURE_FILE_TRANSFER = "SECURE_FILE_TRANSFER"
    REGISTERED_POST = "REGISTERED_POST"
    COURIER = "COURIER"
    IN_PERSON = "IN_PERSON"
    OFFLINE_MEDIA = "OFFLINE_MEDIA"
    MANUAL_OTHER = "MANUAL_OTHER"
    MANUAL_PORTAL = "MANUAL_PORTAL"
    PHYSICAL_SUBMISSION = "PHYSICAL_SUBMISSION"
    MOCK_DISPATCH = "MOCK_DISPATCH"
    SECURE_PORTAL = "SECURE_PORTAL"
    ENCRYPTED_API = "ENCRYPTED_API"
    MANUAL_DISPATCH = "MANUAL_DISPATCH"
    MOCK = "MOCK"
    # Stage 4: an officially authorized, non-production provider sandbox. Kept
    # distinct from OFFICIAL_API (the in-process mock) so the two can never be
    # confused, and refused outright in the MOCK and PRODUCTION environments.
    SANDBOX_API = "SANDBOX_API"


class TransmissionStatus(str, Enum):
    READY_FOR_MANUAL_SUBMISSION = "READY_FOR_MANUAL_SUBMISSION"
    READY_FOR_PHYSICAL_SUBMISSION = "READY_FOR_PHYSICAL_SUBMISSION"
    PENDING = "PENDING"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
    ACKNOWLEDGED = "ACKNOWLEDGED"


class ProviderResponseStatus(str, Enum):
    PROVIDER_QUERY = "PROVIDER_QUERY"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    PROCESSING = "PROCESSING"
    PARTIAL_RESPONSE = "PARTIAL_RESPONSE"
    COMPLETED = "COMPLETED"


class IngestionStatus(str, Enum):
    PENDING = "PENDING"
    INGESTED = "INGESTED"
    FAILED = "FAILED"
    BYPASSED = "BYPASSED"


class IntegrationEnvironment(str, Enum):
    MOCK = "MOCK"
    SANDBOX = "SANDBOX"
    PRODUCTION = "PRODUCTION"


class ProviderIntegrationStatus(str, Enum):
    DRAFT = "DRAFT"
    DOCUMENTATION_VERIFIED = "DOCUMENTATION_VERIFIED"
    SANDBOX_CONFIGURED = "SANDBOX_CONFIGURED"
    CONTRACT_TESTED = "CONTRACT_TESTED"
    SECURITY_REVIEWED = "SECURITY_REVIEWED"
    AGENCY_APPROVED = "AGENCY_APPROVED"
    PROVIDER_APPROVED = "PROVIDER_APPROVED"
    PRODUCTION_ACTIVE = "PRODUCTION_ACTIVE"
    SUSPENDED = "SUSPENDED"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class CertificationResult(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    REQUIRES_MANUAL_REVIEW = "REQUIRES_MANUAL_REVIEW"


class SandboxAuthorizationStatus(str, Enum):
    """Lifecycle of an agency's authorization to use a provider's sandbox."""
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class CertificateType(str, Enum):
    MTLS_CLIENT = "MTLS_CLIENT"
    REQUEST_SIGNING = "REQUEST_SIGNING"
    PROVIDER_VERIFICATION = "PROVIDER_VERIFICATION"

